name: CustomEnchantments
version: ${project.version}
main: me.dannyisyog.CustomEnchantments
api-version: 1.13
description: This is a Minecraft Plugin that adds new enchantments to the game
commands:
  ce addTelepathy:
  ce addTreecapitator:
  ce addBuild:
  ce:
